steps:
- name: 'gcr.io/config-management-release/kpt'
  args:
  - 'cfg'
  - 'cat'
  - '--wrap-kind=ResourceList'
  - '--dest=/workspace/_compiled.yaml'
  - '/workspace/config-root/'
- name: 'gcr.io/config-management-release/policy-controller-validate'	
  args:	
    - "--input=/workspace/_compiled.yaml"	
    - "--output=/workspace/_compiled_checked.yaml"
