steps:
- name: 'gcr.io/kpt-dev/kpt:latest'
  entrypoint: bash
  args:
  - '-c'
  - |
    gcr.io/kpt-dev/kpt cfg cat --wrap-kind=ResourceList  /workspace | 
        docker run  -i gcr.io/kpt-functions/gatekeeper-validate:dev
