steps:
- name: 'gcr.io/kpt-dev/kpt:latest'
  args:
  - 'cfg'
  - 'cat'
  - '--wrap-kind=ResourceList'
  - '--dest=/workspace/_compiled.yaml'
  - '/workspace'
- name: 'gcr.io/kpt-functions/gatekeeper-validate:dev'	
  args:	
    - "--input=/workspace/_compiled.yaml"	
    - "--output=/workspace/_compiled_checked.yaml"
