apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: shift-left-demo
  policyController:
    enabled: true
    templateLibraryInstalled: false
  configConnector:
    enabled: false
  git:
    syncRepo: git@github.com:linde/acm-shift-left.git
    secretType: ssh
    policyDir: config-root
    syncBranch: custom-policy
    
    
